### ISSUE TITLE
Option to remove special chars from title name

### ISSUE THREAD

**Issue by LiskoFINAL** [giwty/switch-library-manager#35] opened 2020-09-11 10:22 UTC
Hi, I successfully use this app to standard rename my xci/nsp files on mac. There's an annoying issue tough. FS service on the switch doesn't recognize all utf-8 special characters like the littles tm, r, c logos in filenames and refuse to show the files with them in, so we have to manually remove them from file name every time we need to transfer files to the switch. Would be nice to have a flag that when enabled skips, remove or remap them to standard characters during library organization.

**Comment by pixeltester** [comment] 2020-09-13 08:12
Duplicate of https://github.com/giwty/switch-library-manager/issues/23

**Comment by giwty** [comment] 2020-09-13 18:45
Fixed in 1.2.5

**Comment by LiskoFINAL** [comment] 2020-09-14 16:56
Hi, nice work thank you. Just for completion the nintendo switch seems to accept file names with accent like à, è, ì, ò and ù. So this couldn't be skipped and help with games such as pokèmon. Although you could also remap them to standard characters so that pokèmom becomes pokemon instead of pokmon.

**Comment by giwty** [comment] 2020-09-14 18:13
Yes, makes sense, i'll fix it

**Comment by giwty** [comment] 2020-09-25 03:06
Hopefully fixed this time

**Closed by giwty** 2020-09-25 03:06 UTC

**Comment by LiskoFINAL** [comment] 2020-09-25 10:29
Thanks I'll test it later. From seeing your nonascii regexp I have a doubt: you included áéíóú which while it's fine it doesn't include àèìòù which are also safe. Not a big loss as I think I don't even have a title with them in but maybe could be

**Comment by tom3220** [comment] 2020-11-12 11:03
Just to add to this with characters that could be included in the nonascii regexp as safe, ö is used in the game Röki which currently gets reduced to 'Rki'.
